// apps/chatwoot/app/javascript/dashboard/components-next/ui/async-select/AsyncSelect.vue
<script setup lang="ts" generic="T">
import type { Ref } from 'vue';
import { computed, onMounted, ref, watch } from 'vue';
import { onClickOutside, refDebounced } from '@vueuse/core';
import { useI18n } from 'vue-i18n';
import { Check, ChevronDown, ChevronsUpDown, Search, X } from '@lucide/vue';
import { Button } from 'next/ui/button';
import { Badge } from 'next/ui/badge';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from 'next/ui/command';

import { Popover, PopoverContent, PopoverTrigger } from 'next/ui/popover';
import { Spinner } from 'next/ui/spinner';
import { cn } from 'next/lib/utils';

defineOptions({ inheritAttrs: false });

const SELECT_ALL_VALUE = '__async_select_all__';

const props = withDefaults(
  defineProps<{
    /** Selected value (string in single mode, string[] in multi mode). */
    modelValue: string | string[];
    /** Static options. Used when no `fetcher` is provided (client-filtered). */
    options?: T[];
    /** Async function that returns the options for a given query. */
    fetcher?: (query?: string) => Promise<T[]>;
    /** Returns the stable value of an option (defaults to `option.value`). */
    getOptionValue?: (option: T) => string;
    /** Returns the display label of an option (defaults to `option.label`). */
    getOptionLabel?: (option: T) => string;
    /** Enable multi-select. */
    multi?: boolean;
    /** When using a fetcher, fetch once and filter locally instead of re-fetching. */
    preload?: boolean;
    /** The consumer owns filtering (drives `options` server-side via `@search`).
     * Skip the built-in client-side label filter so freshly-fetched results
     * aren't re-filtered out (they'd flicker in then vanish). */
    useApiResults?: boolean;
    /** Field label, used to build the default search placeholder. */
    label?: string;
    placeholder?: string;
    /** Overrides the auto-generated search placeholder. */
    searchPlaceholder?: string;
    disabled?: boolean;
    /** Allow toggling off the current value in single mode. */
    clearable?: boolean;
    /** Max badges shown before collapsing to "+N" (multi mode). */
    maxCount?: number;
    hideSelectAll?: boolean;
    width?: string;
    popoverAlign?: 'start' | 'center' | 'end';
    /** Empty-state text (alias kept for ComboBox parity). */
    emptyState?: string;
    notFoundText?: string;
    /** Helper / error text shown below the control. */
    message?: string;
    hasError?: boolean;
    selectAllText?: string;
    clearText?: string;
    closeText?: string;
    triggerClass?: string;
    /** Render the dropdown inline instead of portaling it to <body>. Needed
     * when the select lives inside a panel that closes on outside-click. */
    disablePortal?: boolean;
  }>(),
  {
    options: () => [],
    fetcher: undefined,
    getOptionValue: (option: any) => String(option?.value ?? ''),
    getOptionLabel: (option: any) => String(option?.label ?? ''),
    multi: false,
    preload: false,
    useApiResults: false,
    label: '',
    placeholder: 'Select...',
    searchPlaceholder: '',
    disabled: false,
    clearable: true,
    maxCount: 3,
    hideSelectAll: false,
    width: '',
    popoverAlign: 'start',
    emptyState: '',
    notFoundText: '',
    message: '',
    hasError: false,
    // Empty by default so the i18n fallbacks below apply; pass a prop to override.
    selectAllText: '',
    clearText: '',
    closeText: '',
    triggerClass: '',
    disablePortal: false,
  }
);

const emit = defineEmits<{
  'update:modelValue': [value: string | string[]];
  search: [query: string];
}>();

const { t } = useI18n();

// Footer/select-all labels: use the prop when provided, otherwise fall back to
// the shared translations so every AsyncSelect is localized without each call
// site repeating them.
const selectAllLabel = computed(
  () => props.selectAllText || t('FORMS.MULTISELECT.SELECT_ALL')
);
const clearLabel = computed(() => props.clearText || t('FORMS.MULTISELECT.CLEAR'));
const closeLabel = computed(() => props.closeText || t('FORMS.MULTISELECT.CLOSE'));

const loading = ref(false);
const error = ref<string | null>(null);
const searchTerm = ref('');
const debouncedSearch = refDebounced(searchTerm, 300);
const internalOptions = ref([]) as Ref<T[]>;
const open = ref(false);
const containerRef = ref<HTMLElement | null>(null);

// reka's own outside-click dismissal doesn't fire reliably for this
// Popover+Command combo (the dropdown gets stuck open, blocking the page), so
// we close it ourselves. `ignore` keeps clicks inside the dropdown from closing
// it — matched by `data-slot` so it works whether the content is portaled to
// <body> or rendered inline (disablePortal).
onClickOutside(
  containerRef,
  () => {
    if (open.value) open.value = false;
  },
  { ignore: ['[data-slot="popover-content"]'] }
);

function selectSingle(value: string) {
  if (!props.clearable && value === selectedValue.value) {
    return;
  }

  emit('update:modelValue', value);
  open.value = false;
}

function toggleValue(value: string) {
  const current = [...selectedValues.value];

  if (current.includes(value)) {
    emit(
      'update:modelValue',
      current.filter(v => v !== value)
    );
  } else {
    emit('update:modelValue', [...current, value]);
  }
}
const usesFetcher = computed(() => typeof props.fetcher === 'function');

// Cache so the labels of selected values survive being filtered out. Typed as a
// concrete Ref so Vue's UnwrapRefSimple<T> doesn't rewrite the Map value type
// (which would break the `T` generic at .set()/.get() call sites). Deep ref is
// intentional — `.set()` must trigger the label computeds when options load.
const optionCache = ref(new Map<string, T>()) as Ref<Map<string, T>>;
const cacheOptions = (opts: T[]) =>
  opts.forEach(opt => optionCache.value.set(props.getOptionValue(opt), opt));

const isMulti = computed(() => props.multi);
const selectedValues = computed<string[]>(() =>
  isMulti.value ? ((props.modelValue as string[]) ?? []) : []
);
const selectedValue = computed<string>(() =>
  isMulti.value ? '' : ((props.modelValue as string) ?? '')
);

const searchPlaceholder = computed(
  () =>
    props.searchPlaceholder ||
    (props.label ? `Buscar ${props.label.toLowerCase()}...` : 'Buscar...')
);
const emptyText = computed(
  () =>
    props.notFoundText ||
    props.emptyState ||
    (props.label
      ? `Nenhum ${props.label.toLowerCase()} encontrado.`
      : 'Nada encontrado.')
);

const filteredOptions = computed(() => {
  // Consumer-driven (server-side) search or a fetcher owns the filtering:
  // render exactly what we were given, otherwise the client-side label filter
  // strips out freshly-fetched results (they appear then disappear).
  if (props.useApiResults) {
    return internalOptions.value;
  }

  if (usesFetcher.value && !props.preload) {
    return internalOptions.value;
  }

  const query = searchTerm.value.toLowerCase();

  return internalOptions.value.filter(option =>
    props.getOptionLabel(option).toLowerCase().includes(query)
  );
});

const load = async (query?: string) => {
  if (!props.fetcher) return;
  loading.value = true;
  error.value = null;
  try {
    const data = await props.fetcher(query);
    internalOptions.value = data;
    cacheOptions(data);
  } catch (err) {
    error.value =
      err instanceof Error ? err.message : 'Failed to fetch options';
  } finally {
    loading.value = false;
  }
};

// Static `options` mode: mirror the prop into the rendered list (reka filters).
watch(
  () => props.options,
  opts => {
    if (!usesFetcher.value) {
      internalOptions.value = opts ?? [];
      cacheOptions(internalOptions.value);
    }
  },
  { immediate: true }
);

onMounted(() => {
  if (usesFetcher.value) load();
});

// Re-fetch (server-side search) only when the fetcher owns the filtering.
watch(debouncedSearch, query => {
  emit('search', query ?? '');
  if (usesFetcher.value && !props.preload) load(query);
});

const isSelected = (value: string) =>
  isMulti.value
    ? selectedValues.value.includes(value)
    : selectedValue.value === value;

const labelFor = (value: string) => {
  const option = optionCache.value.get(value);
  return option ? props.getOptionLabel(option) : value;
};

const selectedSingleLabel = computed(() =>
  selectedValue.value ? labelFor(selectedValue.value) : ''
);

const allSelected = computed(
  () =>
    internalOptions.value.length > 0 &&
    selectedValues.value.length === internalOptions.value.length
);

const handleClear = () => emit('update:modelValue', isMulti.value ? [] : '');

const removeValue = (value: string) =>
  emit(
    'update:modelValue',
    selectedValues.value.filter(item => item !== value)
  );

const toggleAll = () => {
  const all = internalOptions.value.map(props.getOptionValue);
  emit('update:modelValue', allSelected.value ? [] : all);
};

const contentStyle = computed(() => ({
  width: props.width || 'var(--reka-popper-anchor-width)',
}));
const triggerStyle = computed(() =>
  props.width ? { width: props.width } : undefined
);
</script>

<template>
  <div
    ref="containerRef"
    :class="cn('relative min-w-0', !width && 'w-full')"
    v-bind="$attrs"
  >
    <Popover v-model:open="open">
      <PopoverTrigger as-child>
        <!-- Custom trigger (e.g. a "+ tag" button); falls back to the
             default value-showing trigger when no slot is provided. -->
        <slot name="trigger">
          <!-- Single Select -->
          <Button
            v-if="!isMulti"
            type="button"
            variant="outline"
            role="combobox"
            :aria-expanded="open"
            :disabled="disabled"
            :class="
              cn(
                'h-9 w-full justify-between',
                disabled && 'cursor-not-allowed opacity-50',
                hasError &&
                  'border-destructive text-destructive hover:bg-destructive/10',
                triggerClass
              )
            "
          >
            <span class="truncate">
              {{ selectedSingleLabel || placeholder }}
            </span>

            <ChevronsUpDown class="opacity-50" />
          </Button>

          <!-- Multi Select -->
          <div
            v-else
            role="combobox"
            :aria-expanded="open"
            :class="
              cn(
                'border-border bg-background ring-offset-background placeholder:text-muted-foreground focus:ring-ring flex h-9 w-full min-w-[160px] cursor-pointer items-center justify-between rounded-md border px-2 py-0.5 text-sm focus:outline-none focus:ring-2 focus:ring-offset-2',
                disabled && 'cursor-not-allowed opacity-50',
                hasError &&
                  'border-destructive text-destructive hover:bg-destructive/10'
              )
            "
          >
            <template v-if="selectedValues.length">
              <div
                class="flex max-h-20 min-w-0 flex-1 flex-wrap items-center gap-1 overflow-y-auto pr-2"
              >
                <div
                  v-for="val in selectedValues.slice(0, maxCount)"
                  :key="val"
                  class="hover:text-primary flex h-[26px] flex-shrink-0 items-center gap-1 rounded-md border border-zinc-200 px-2 py-0.5 text-zinc-600 hover:border-zinc-400 dark:border-zinc-700 dark:text-zinc-400 dark:hover:border-zinc-600"
                >
                  <div
                    class="flex max-w-[100px] items-center gap-1 truncate text-xs"
                  >
                    {{ labelFor(val) }}
                  </div>

                  <X
                    class="box-content h-3 w-3 shrink-0 cursor-pointer rounded-full p-1 text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800"
                    @click.stop="removeValue(val)"
                  />
                </div>

                <div
                  v-if="selectedValues.length > maxCount"
                  class="flex-shrink-0"
                >
                  <Badge variant="outline">
                    +{{ selectedValues.length - maxCount }}
                  </Badge>
                </div>
              </div>

              <div class="flex shrink-0 items-center gap-1">
                <X
                  class="box-content h-3 w-3 shrink-0 cursor-pointer rounded-full p-1 text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800"
                  @click.stop="handleClear"
                />

                <div class="bg-border h-5 w-px" />

                <ChevronDown
                  class="size-4 cursor-pointer text-zinc-300 dark:text-zinc-500"
                />
              </div>
            </template>

            <div v-else class="flex w-full items-center justify-between">
              <span class="text-muted-foreground">
                {{ placeholder }}
              </span>

              <ChevronDown
                class="size-4 cursor-pointer text-zinc-300 dark:text-zinc-500"
              />
            </div>
          </div>
        </slot>
      </PopoverTrigger>

      <PopoverContent
        :align="popoverAlign"
        :style="contentStyle"
        :disable-portal="disablePortal"
        class="p-0"
      >
        <!-- We own filtering (static `options`/server-side `fetcher`); disable
             Command's built-in text filter so async results aren't hidden. -->
        <Command :should-filter="false">
          <div class="relative w-full">
            <CommandInput
              v-model="searchTerm"
              :placeholder="searchPlaceholder"
            />

            <div
              v-if="loading && internalOptions.length"
              class="absolute right-2 top-1/2 flex -translate-y-1/2 items-center"
            >
              <Spinner />
            </div>
          </div>

          <CommandList>
            <CommandEmpty>
              <div class="py-6 text-center text-sm">
                {{ error || emptyText }}
              </div>
            </CommandEmpty>

            <CommandGroup
              v-if="loading && !internalOptions.length"
              class="py-4"
            >
              <div class="flex justify-center">
                <Spinner />
              </div>
            </CommandGroup>

            <CommandGroup
              v-if="internalOptions.length"
              class="max-h-[300px] overflow-y-auto"
            >
              <!-- Select All -->
              <CommandItem
                v-if="isMulti && !hideSelectAll && filteredOptions.length"
                :value="SELECT_ALL_VALUE"
                class="cursor-pointer"
                @select="toggleAll"
              >
                <span
                  :class="
                    cn(
                      'border-primary shadow-sm mr-1 flex size-4 items-center justify-center rounded-[4px] border outline-none transition-shadow',
                      allSelected
                        ? 'border-primary bg-primary text-primary-foreground'
                        : 'opacity-50 [&_svg]:invisible'
                    )
                  "
                >
                  <Check v-if="allSelected" class="size-3.5" />
                </span>

                {{ selectAllLabel }}
              </CommandItem>

              <!-- Options -->
              <CommandItem
                v-for="option in filteredOptions"
                class="cursor-pointer"
                :key="getOptionValue(option)"
                :value="getOptionLabel(option)"
                @select="
                  () =>
                    isMulti
                      ? toggleValue(getOptionValue(option))
                      : selectSingle(getOptionValue(option))
                "
              >
                <span
                  v-if="isMulti"
                  :class="
                    cn(
                      'border-primary shadow-sm mr-1 flex size-4 items-center justify-center rounded-[4px] border outline-none transition-shadow',
                      isSelected(getOptionValue(option))
                        ? 'border-primary bg-primary text-primary-foreground'
                        : 'opacity-50 [&_svg]:invisible'
                    )
                  "
                >
                  <Check
                    v-if="isSelected(getOptionValue(option))"
                    class="size-3.5"
                  />
                </span>

                <slot name="option" :option="option">
                  <span class="truncate">
                    {{ getOptionLabel(option) }}
                  </span>
                </slot>

                <Check
                  v-if="!isMulti"
                  :class="
                    cn(
                      'ml-auto h-3 w-3',
                      isSelected(getOptionValue(option))
                        ? 'opacity-100'
                        : 'opacity-0'
                    )
                  "
                />
              </CommandItem>
            </CommandGroup>
          </CommandList>

          <!-- Footer — must live INSIDE <Command> so CommandSeparator/
               CommandGroup can inject the CommandContext; otherwise they throw
               ("must be used within Command") the moment a value is selected in
               multi mode, crashing the whole dropdown. -->
          <CommandSeparator v-if="isMulti && selectedValues.length" />

          <CommandGroup v-if="isMulti && selectedValues.length">
            <div class="flex items-center p-1">
              <button
                type="button"
                class="hover:bg-accent flex-1 cursor-pointer rounded-sm px-2 py-1.5 text-center text-sm"
                @click="handleClear"
              >
                {{ clearLabel }}
              </button>

              <div class="bg-border mx-1 h-5 w-px" />

              <button
                type="button"
                class="hover:bg-accent flex-1 cursor-pointer rounded-sm px-2 py-1.5 text-center text-sm"
                @click="open = false"
              >
                {{ closeLabel }}
              </button>
            </div>
          </CommandGroup>
        </Command>
      </PopoverContent>
    </Popover>

    <p
      v-if="message"
      class="mt-2 mb-0 truncate text-xs"
      :class="hasError ? 'text-destructive' : ''"
    >
      {{ message }}
    </p>
  </div>
</template>

// libs/ui/src/components/ui/async-select.tsx
import { useCallback, useEffect, useState } from 'react';
import { Badge } from '@nestposts/ui/components/ui/badge';
import { Button } from '@nestposts/ui/components/ui/button';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from '@nestposts/ui/components/ui/command';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@nestposts/ui/components/ui/popover';
import { Separator } from '@nestposts/ui/components/ui/separator';
import { useDebounce } from '@nestposts/ui/hooks/use-debounce';
import { cn } from '@nestposts/ui/lib/utils';
import {
  Check,
  CheckIcon,
  ChevronDown,
  ChevronsUpDown,
  Loader2,
  X,
} from 'lucide-react';

export interface Option {
  value: string;
  label: string;
  disabled?: boolean;
  description?: string;
  icon?: React.ReactNode;
}

export interface AsyncSelectBaseSingleProps<_T> {
  multi?: false;
  value: string;
  onChange: (value: string) => void;
}

export interface AsyncSelectBaseMultiProps<_T> {
  multi: true;
  value: string[];
  onChange: (value: string[]) => void;
  maxCount?: number;
  clearText?: string;
  closeText?: string;
  hideSelectAll?: boolean;
  clearSearchOnClose?: boolean;
}

export interface AsyncSelectCommonProps<T> {
  fetcher: (query?: string) => Promise<T[]>;
  preload?: boolean;
  filterFn?: (option: T, query: string) => boolean;
  renderOption: (option: T) => React.ReactNode;
  getOptionValue: (option: T) => string;
  getDisplayValue: (option: T) => React.ReactNode;
  notFound?: React.ReactNode;
  loadingSkeleton?: React.ReactNode;
  label: string;
  placeholder?: string;
  disabled?: boolean;
  width?: string | number;
  popoverAlign?: 'start' | 'center' | 'end';
  className?: string;
  triggerClassName?: string;
  selectAllText?: string;
  noResultsMessage?: string;
  clearable?: boolean;
}

export type AsyncSelectProps<T> = AsyncSelectCommonProps<T> &
  (AsyncSelectBaseSingleProps<T> | AsyncSelectBaseMultiProps<T>);

export function AsyncSelect<T>(props: AsyncSelectProps<T>) {
  const {
    fetcher,
    preload,
    filterFn,
    renderOption,
    getOptionValue,
    getDisplayValue,
    notFound,
    loadingSkeleton,
    label,
    placeholder = 'Select...',
    value,
    onChange,
    disabled = false,
    width = '200px',
    popoverAlign = 'center',
    className,
    triggerClassName,
    noResultsMessage,
    clearable = true,
    selectAllText = 'Select all',
  } = props;

  const multi = 'multi' in props && props.multi;
  const maxCount = multi && 'maxCount' in props ? props.maxCount || 3 : 3;
  const clearText =
    multi && 'clearText' in props ? props.clearText || 'Clear' : 'Clear';
  const closeText =
    multi && 'closeText' in props ? props.closeText || 'Close' : 'Close';
  const hideSelectAll =
    multi && 'hideSelectAll' in props ? props.hideSelectAll || false : false;
  const clearSearchOnClose =
    multi && 'clearSearchOnClose' in props
      ? props.clearSearchOnClose || false
      : false;

  const [mounted, setMounted] = useState(false);
  const [open, setOpen] = useState(false);
  const [options, setOptions] = useState<T[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const debouncedSearchTerm = useDebounce(searchTerm, preload ? 0 : 300);
  const [originalOptions, setOriginalOptions] = useState<T[]>([]);

  const [selectedValue, setSelectedValue] = useState(
    multi ? [] : (value as string),
  );
  const [selectedOption, setSelectedOption] = useState<T | null>(null);

  const [selectedValues, setSelectedValues] = useState<string[]>(
    multi ? (value as string[]) || [] : [],
  );
  const [selectedOptions, setSelectedOptions] = useState<T[]>([]);

  useEffect(() => {
    setMounted(true);
    if (multi) {
      setSelectedValues((value as string[]) || []);
    } else {
      setSelectedValue(value as string);
    }
  }, [value, multi]);

  useEffect(() => {
    if (options.length > 0) {
      if (multi) {
        const multiValue = value as string[];
        if (multiValue && multiValue.length > 0) {
          const matchedOptions = multiValue
            .map((val) => options.find((opt) => getOptionValue(opt) === val))
            .filter(Boolean) as T[];
          setSelectedOptions(matchedOptions);
        }
      } else {
        const singleValue = value as string;
        if (singleValue) {
          const option = options.find(
            (opt) => getOptionValue(opt) === singleValue,
          );
          if (option) {
            setSelectedOption(option);
          }
        }
      }
    }
  }, [value, options, getOptionValue, multi]);

  useEffect(() => {
    const initializeOptions = async () => {
      try {
        setLoading(true);
        setError(null);
        const data = await fetcher();
        setOriginalOptions(data);
        setOptions(data);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : 'Failed to fetch options',
        );
      } finally {
        setLoading(false);
      }
    };

    if (!mounted) {
      initializeOptions();
    }
  }, [mounted, fetcher]);

  useEffect(() => {
    const fetchOptions = async () => {
      try {
        setLoading(true);
        setError(null);
        const data = await fetcher(debouncedSearchTerm);
        setOriginalOptions(data);
        setOptions(data);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : 'Failed to fetch options',
        );
      } finally {
        setLoading(false);
      }
    };

    if (!mounted) {
      fetchOptions();
    } else if (!preload) {
      fetchOptions();
    } else if (preload) {
      if (debouncedSearchTerm) {
        setOptions(
          originalOptions.filter((option) =>
            filterFn ? filterFn(option, debouncedSearchTerm) : true,
          ),
        );
      } else {
        setOptions(originalOptions);
      }
    }
  }, [fetcher, debouncedSearchTerm, mounted, preload, filterFn]);

  const handleSelect = useCallback(
    (currentValue: string) => {
      if (multi) {
        const multiOnChange = onChange as (value: string[]) => void;
        const currentValues = selectedValues;
        const isSelected = currentValues.includes(currentValue);
        const newValues = isSelected
          ? currentValues.filter((val) => val !== currentValue)
          : [...currentValues, currentValue];

        setSelectedValues(newValues);
        setSelectedOptions(
          newValues
            .map((val) =>
              options.find((option) => getOptionValue(option) === val),
            )
            .filter(Boolean) as T[],
        );
        multiOnChange(newValues);
      } else {
        const singleOnChange = onChange as (value: string) => void;
        const newValue =
          clearable && currentValue === selectedValue ? '' : currentValue;
        setSelectedValue(newValue);
        setSelectedOption(
          options.find((option) => getOptionValue(option) === newValue) || null,
        );
        singleOnChange(newValue);
        setOpen(false);
      }
    },
    [
      selectedValue,
      selectedValues,
      onChange,
      clearable,
      options,
      getOptionValue,
      multi,
    ],
  );

  const handleClear = useCallback(() => {
    if (multi) {
      const multiOnChange = onChange as (value: string[]) => void;
      setSelectedValues([]);
      setSelectedOptions([]);
      multiOnChange([]);
    } else {
      const singleOnChange = onChange as (value: string) => void;
      setSelectedValue('');
      setSelectedOption(null);
      singleOnChange('');
    }
  }, [onChange, multi]);

  const handleInputKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter') {
      setOpen(true);
    } else if (
      event.key === 'Backspace' &&
      !event.currentTarget.value &&
      multi
    ) {
      const newSelectedValues = [...selectedValues];
      newSelectedValues.pop();
      setSelectedValues(newSelectedValues);
      setSelectedOptions(
        newSelectedValues
          .map((val) =>
            options.find((option) => getOptionValue(option) === val),
          )
          .filter(Boolean) as T[],
      );
      (onChange as (value: string[]) => void)(newSelectedValues);
    }
  };

  const toggleAll = useCallback(() => {
    if (!multi) return;
    const multiOnChange = onChange as (value: string[]) => void;

    if (selectedValues.length === options.length) {
      setSelectedValues([]);
      setSelectedOptions([]);
      multiOnChange([]);
    } else {
      const allValues = options.map((option) => getOptionValue(option));
      setSelectedValues(allValues);
      setSelectedOptions(options);
      multiOnChange(allValues);
    }
  }, [selectedValues, options, onChange, getOptionValue, multi]);

  const clearExtraOptions = useCallback(() => {
    if (!multi) return;
    const multiOnChange = onChange as (value: string[]) => void;
    const newSelectedValues = selectedValues.slice(0, maxCount);
    setSelectedValues(newSelectedValues);
    setSelectedOptions(
      newSelectedValues
        .map((val) => options.find((option) => getOptionValue(option) === val))
        .filter(Boolean) as T[],
    );
    multiOnChange(newSelectedValues);
  }, [selectedValues, maxCount, options, onChange, getOptionValue, multi]);

  const removeValue = useCallback(
    (valueToRemove: string) => {
      if (!multi) return;
      const multiOnChange = onChange as (value: string[]) => void;
      const newValues = selectedValues.filter((val) => val !== valueToRemove);
      setSelectedValues(newValues);
      setSelectedOptions(
        newValues
          .map((val) =>
            options.find((option) => getOptionValue(option) === val),
          )
          .filter(Boolean) as T[],
      );
      multiOnChange(newValues);
    },
    [selectedValues, options, onChange, getOptionValue, multi],
  );

  const renderSingleTrigger = () => (
    <Button
      variant="outline"
      role="combobox"
      aria-expanded={open}
      className={cn(
        'justify-between',
        disabled && 'cursor-not-allowed opacity-50',
        triggerClassName,
      )}
      {...(typeof width === 'string'
        ? { style: { width } }
        : { className: `w-[${width}px]` })}
      disabled={disabled}
    >
      {selectedOption ? getDisplayValue(selectedOption) : placeholder}
      <ChevronsUpDown className="opacity-50" size={10} />
    </Button>
  );

  const renderMultiTrigger = () => (
    <div
      className={cn(
        'flex h-auto min-h-[36px] w-full min-w-[160px] cursor-pointer items-center justify-between rounded-md border border-input bg-background px-2 py-0.5 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50',
        disabled && 'cursor-not-allowed opacity-50',
        triggerClassName,
      )}
      {...(typeof width === 'string'
        ? { style: { width } }
        : { className: `w-[${width}px]` })}
    >
      {selectedValues.length > 0 ? (
        <div className="flex w-full items-center justify-between">
          <div className="flex max-h-20 min-w-0 flex-1 flex-wrap items-center gap-1 overflow-y-auto pr-2">
            {selectedValues.slice(0, maxCount).map((val) => {
              const option = selectedOptions.find(
                (opt) => getOptionValue(opt) === val,
              );
              return (
                <div
                  className="flex h-[26px] flex-shrink-0 items-center gap-1 rounded-md border border-zinc-200 px-2 py-0.5 text-zinc-600 hover:border-zinc-400 hover:text-primary dark:border-zinc-700 dark:text-zinc-400 dark:hover:border-zinc-600 dark:hover:text-primary"
                  key={val}
                >
                  <div className="flex max-w-[100px] items-center gap-1 truncate text-xs">
                    {option ? getDisplayValue(option) : val}
                  </div>
                  <X
                    className="box-content h-3 w-3 shrink-0 cursor-pointer rounded-full p-1 text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800"
                    onClick={(event) => {
                      event.stopPropagation();
                      removeValue(val);
                    }}
                  />
                </div>
              );
            })}
            {selectedValues.length > maxCount && (
              <Badge variant="outline" className="flex-shrink-0">
                <span>{`+ ${selectedValues.length - maxCount}`}</span>
                <X
                  className="ml-2 box-content h-3 w-3 shrink-0 cursor-pointer rounded-full p-1 text-zinc-300 hover:bg-zinc-100 hover:text-primary dark:text-zinc-500 dark:hover:bg-zinc-800"
                  onClick={(event) => {
                    event.stopPropagation();
                    clearExtraOptions();
                  }}
                />
              </Badge>
            )}
          </div>
          <div className="flex flex-shrink-0 items-center justify-between">
            <X
              className="ml-2 box-content h-4 w-4 shrink-0 cursor-pointer rounded-full p-1 text-zinc-300 hover:bg-zinc-100 hover:text-primary dark:text-zinc-500 dark:hover:bg-zinc-800"
              onClick={(event) => {
                event.stopPropagation();
                handleClear();
              }}
            />
            <Separator
              orientation="vertical"
              className="mx-2 flex h-full min-h-6"
            />
            <ChevronDown className="h-4 cursor-pointer text-zinc-300 hover:text-primary dark:text-zinc-500" />
          </div>
        </div>
      ) : (
        <div className="mx-auto flex w-full items-center justify-between">
          <span className="font-normal text-[12px] text-zinc-500">
            {placeholder}
          </span>
          <ChevronDown className="h-4 cursor-pointer text-zinc-300 dark:text-zinc-500" />
        </div>
      )}
    </div>
  );

  return (
    <Popover
      open={open}
      onOpenChange={(newOpen) => {
        setOpen(newOpen);
        if (!newOpen && clearSearchOnClose && multi) {
          setSearchTerm('');
        }
      }}
    >
      <PopoverTrigger
        render={multi ? renderMultiTrigger() : renderSingleTrigger()}
      />
      <PopoverContent
        align={popoverAlign}
        {...(typeof width === 'string'
          ? { style: { width } }
          : { className: `w-[${width}px]` })}
        className={cn('p-0', className)}
      >
        <Command shouldFilter={false}>
          <div className="relative w-full border-b">
            <CommandInput
              placeholder={`Buscar ${label.toLowerCase()}...`}
              value={searchTerm}
              onValueChange={(value) => {
                setSearchTerm(value);
              }}
              onKeyDown={handleInputKeyDown}
            />
            {loading && options.length > 0 && (
              <div className="absolute top-1/2 right-2 flex -translate-y-1/2 transform items-center">
                <Loader2 className="h-4 w-4 animate-spin" />
              </div>
            )}
          </div>
          <CommandList className="max-h-[400px] overflow-y-auto">
            {error && (
              <div className="p-4 text-center text-destructive">{error}</div>
            )}
            {loading &&
              options.length === 0 &&
              (loadingSkeleton || <DefaultLoadingSkeleton />)}
            {!loading &&
              !error &&
              options.length === 0 &&
              (notFound || (
                <CommandEmpty>
                  {noResultsMessage ?? `No ${label.toLowerCase()} found.`}
                </CommandEmpty>
              ))}
            <CommandGroup>
              {multi && !hideSelectAll && (
                <CommandItem
                  key="all"
                  onSelect={toggleAll}
                  className="cursor-pointer"
                >
                  <div
                    className={cn(
                      'mr-1 flex size-4 items-center justify-center rounded-[4px] border border-primary shadow-xs outline-none transition-shadow',
                      selectedValues.length === options.length
                        ? 'border-primary bg-primary text-primary-foreground'
                        : 'opacity-50 [&_svg]:invisible',
                    )}
                  >
                    <CheckIcon className="size-3.5 text-white dark:text-black" />
                  </div>
                  <span>{selectAllText}</span>
                </CommandItem>
              )}
              {options.map((option) => {
                const optionValue = getOptionValue(option);
                const isSelected = multi
                  ? selectedValues.includes(optionValue)
                  : selectedValue === optionValue;

                return (
                  <CommandItem
                    key={optionValue}
                    value={optionValue}
                    onSelect={handleSelect}
                    className="cursor-pointer"
                  >
                    {multi && (
                      <div
                        className={cn(
                          'mr-1 flex size-4 items-center justify-center rounded-[4px] border border-primary shadow-xs outline-none transition-shadow',
                          isSelected
                            ? 'border-primary bg-primary text-primary-foreground'
                            : 'opacity-50 [&_svg]:invisible',
                        )}
                      >
                        <CheckIcon className="size-3.5 text-white dark:text-black" />
                      </div>
                    )}
                    {renderOption(option)}
                    {!multi && (
                      <Check
                        className={cn(
                          'ml-auto h-3 w-3',
                          isSelected ? 'opacity-100' : 'opacity-0',
                        )}
                      />
                    )}
                  </CommandItem>
                );
              })}
            </CommandGroup>
            {multi && (
              <>
                <CommandSeparator />
                <CommandGroup>
                  <div className="flex items-center justify-between">
                    {selectedValues.length > 0 && (
                      <>
                        <CommandItem
                          onSelect={handleClear}
                          className="flex-1 cursor-pointer justify-center"
                        >
                          {clearText}
                        </CommandItem>
                        <Separator
                          orientation="vertical"
                          className="flex h-full min-h-6"
                        />
                      </>
                    )}
                    <CommandItem
                      onSelect={() => setOpen(false)}
                      className="max-w-full flex-1 cursor-pointer justify-center"
                    >
                      {closeText}
                    </CommandItem>
                  </div>
                </CommandGroup>
              </>
            )}
          </CommandList>
        </Command>
      </PopoverContent>
    </Popover>
  );
}

function DefaultLoadingSkeleton() {
  return (
    <CommandGroup>
      {[1, 2, 3].map((i) => (
        <CommandItem key={i} disabled>
          <div className="flex w-full items-center gap-2">
            <div className="h-6 w-6 animate-pulse rounded-full bg-muted" />
            <div className="flex flex-1 flex-col gap-1">
              <div className="h-4 w-24 animate-pulse rounded bg-muted" />
              <div className="h-3 w-16 animate-pulse rounded bg-muted" />
            </div>
          </div>
        </CommandItem>
      ))}
    </CommandGroup>
  );
}
